Proofread
sysprog21/cpumemory-zhtw pull request #8
Opened 2024-06-25 17:51 UTC by st10740

* Try rewriting the sentence to make it smoother
* Correct the mistranslated Chinese for 'process'
* Translate the untranslated sentence

2024-06-25 17:53 UTC, jserv requested changes
Read https://cbea.ms/git-commit/ carefully and refine the git commit messages.

2024-06-26 15:16 UTC, jserv requested changes
Avoid writing "Update <filename>" as the subject of git commits. Instead, you can say "Proofread <subsection name>". The message body should consist of complete English sentences if you want to explain something.

2024-06-26 15:17 UTC, jserv commented on commodity-hardware-today/ram-types/dynamic-ram.md
> +一個動態 RAM 的記憶單元在電容 $$ \mathbf{C} $$ 中保存其狀態。電晶體 $$ \mathbf{M} $$ 用以控制狀態的存取。為了讀取記憶單元的狀態，要提高存取線路 $$ \mathbf{AL} $$ 的電位；這要不使得電流流經資料線路（data line） $$ \mathbf{DL} $$、要不沒有，取決於電容中的電量。要寫到記憶單元中，則要適當地設置資料線路 $$ \m
Check the part "以讓電容充電或放電的時間".

2024-06-26 15:22 UTC, jserv commented on virtual-memory/impact-of-virtualization.md
> +在 Xen 的情況下（見圖 4.4），Xen VMM 即是這個軟體。不過 VMM 本身並不實作太多其它的硬體控制。不若在其它較早期的系統（以及首次釋出的 Xen VMM）上的 VMM，除了記憶體與處理器之外的硬體是由具有特權的 Dom0 域所控制的。目前，這基本上是與沒有特權的 DomU 系統核心具有相同的系統核心，而且 –– 就所關心的記憶體管理而言 –– 它們沒什麼區別。重要的是，VMM 將
Replace "這基本上是與沒有特權的 DomU 系統核心具有相同的系統核心" with "這跟運作於非特權模式的 DomU 具備相同的系統核心"

> Unlike VMMs on other, earlier systems (and the first release of the Xen VMM) the hardware outside of memory and processors is controlled by the privileged Dom0 domain. Currently, this is basically the same kernel as the unprivileged DomU kernels and, as far as memory handling is concerned, they do not differ. Important here is that the VMM hands out physical memory to the Dom0 and DomU kernels which, themselves, then implement the usual memory handling as if they were running directly on a processor.

2024-06-26 15:23 UTC, jserv commented on virtual-memory/optimizing-page-table-access/influencing-tlb-performance.md
> +只是現在所需的對齊尺寸更大。
Refine this statement.

2024-06-27 03:13 UTC, st10740 commented
I revised the above issues.

2024-06-27 03:16 UTC, jserv commented
> I revised the above issues.

No, you shall avoid placing filenames in the subject of git commits.

2024-06-27 03:19 UTC, jserv commented
Instead of "Proofread multi-level-page-tables.md // I change the translation about two level 2 page directories needed
to make the sentence more fluent," you should denote the paragraph you have modified along with the motivations.

2024-06-27 16:01 UTC, st10740 commented
I replaced the filenames in the subject of git commits with simple description about the sentences I modified, and explained the reason why I modified them in the message body.

2024-06-27 16:08 UTC, merged

2024-06-27 16:08 UTC, jserv commented
Thank @st10740 for contributing!